T6540: added workflows (current)
vyos/vyatta-bash pull request #3
Opened 2024-07-03 18:48 UTC by kumvijaya

## Change Summary

T6540: added workflows (current)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6540

## Related PR(s)

## Proposed changes

## How to test

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-07-03 18:49 UTC, kumvijaya commented
@Mergifyio backport circinus sagitta equuleus

2024-07-03 18:56 UTC, sever-sever approved these changes

2024-07-03 19:21 UTC, c-po requested changes

2024-07-03 19:21 UTC, c-po commented on .github/workflows/lint-j2.yml
> +  name: J2 Lint
There i no J2 lint in vyatta-bash.

j2lint is ONLY supported in vyos-1x

2024-07-04 10:10 UTC, kumvijaya commented on .github/workflows/lint-j2.yml
> +  name: J2 Lint
Removed

2024-07-04 11:38 UTC, dmbaturin approved these changes

2024-07-04 13:50 UTC, c-po approved these changes

2024-07-04 13:50 UTC, merged